<?php

/**
 * Implements hook_install().
 */
function menu_link_weight_extended_install() {
  module_set_weight('menu_link_weight_extended', 11);
  \Drupal::configFactory()->getEditable('menu_link_weight.settings')
    ->set('menu_parent_form_selector', 'cshs')
    ->save();
}

/**
 * Set module weight.
 */
function menu_link_weight_extended_update_8100() {
  module_set_weight('menu_link_weight_extended', 11);
}
