<?php

/**
 * @file
 * Contains menu_link_weight_extended.module..
 */

/**
 * Implements hook_entity_type_build()
 *
 * Add the menu_link_weight_extended form controllers to the entity type config object.
 */
function menu_link_weight_extended_entity_type_build(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['menu']->setFormClass('edit_menu_link_weight_extended', 'Drupal\menu_link_weight_extended\MenuFormLinkController');
  $entity_types['menu']->setFormClass('edit_menu_link_weight_extended_slice', 'Drupal\menu_link_weight_extended\MenuSliceFormController');
}
